---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cnpg-r2-creds
  namespace: cnpg-system
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgBqfSaLMZAK/XSrbtCL3ALfKncclElstji9/dX9U6PHWIf9C7QQMezWsp6E+/UBde65rILT8h/OeKvJt4kbl5J328+G4PdzvtERrzOte1KYmZgTxVDE1+cfJMXum5X8KIyOufB+VJXHNsRbfNKqzpiJAqgQVJJXJKFBxqAB6T/MIoEJ4bPRfPGnem/05N0c29Od5h+/rG/oG93N1O3xFUrrck8k2hM3EWz6A8v+dOTgYcseP+QZL/Valx2s2ySNt83jnbrIu4VjXWjiVV0RIWb5QEMTAMRZRBWwmbeid0LiNhQeOWjzbXBYatulPnV29KpbV1FEHPCn1Nu1qfK+sF/rQgQGOp+5Ie1zXBRcH9vcqmXNvazMB8iK9fU0AV6+mAwrhPYtuxR5A/aAwFF7CWipxApwytSEuBqkfJryREWICEekW1KynqcsIfwRLwXtk2oXMDeoBMGjDgUvYsXMkQxbQIMW2PzqT/tad2nse7JBQzjviaA6G084u7EvBH/l9AeQl6ie46a7H7PGx1Xd3YQhY3z17APY0EKNoHF8w4nommL/iwnii/NuHGT5ZoT5+14zGtJyUEHZXBwqAu7DHyiBXNF3FIeWidJ7/nbxaXQvMfpXugC6V3AeMR7YmYBAFKUdUKBaxvip9eLqHQT0PJJq3EV8nlDDVYy/42X9j5bGrB+NkihNDAXc8lbJgEGKtA8m1tFsl5upRmoCW6E59bFJZxAjaTaZmJuoKLVfopr1ww==
    AWS_SECRET_ACCESS_KEY: AgBPD+gG7BgvvIPwke9f0mG/hFKzTU7W36Y1HpFL+pRkJziXv6oPBqiCC6XN50Qq79cw6iYG1yfNEZEX9efth4B4s50MW7VSf54vlaEMQ4yP6mcGdhaPJjXLZORgclu6vV4CyME05UKmZIshET81CwdZYjLM2OoIzfufC+nvlX20Fjiw19tQec7LPmvQS7UZK9GA1GNa9cXWg7eu0jpFBRrhXunYwx1iwcfRikoeclEavwAcGgZnjC2j3oUITgJ/vKFJxNdw91W475sxGbaeUrZ/K8WRKXzqfyIxVE39ldEVSSQMQDy/ctZIdoncswtkzk4BiPTrFCMDOxs2G3THischyYDVhXcUdm70UF5hYXSLbZdEL8KrGm+9uaiKIVQowhOroQ8H5kkwOF/TAi6TyT/bRlQiXG1RPHsswZDiQGgvP5oCZSRnmnLRPELsR4Yq+fZxZCOFyywhYxI4J+8Vs4sqYiP3tehBHGYAiYyI6BZJu/X8Ff9QtOxBVNRHX2gZwbP3YBwopckATCPrBON44xoKVyeT8PXwEB50h20ttgnAWdMpp1SvE2Km2AEgZ1GqMy7hEyqfIC7/aq6J3l1+CqUrXgAB1ObeLxx8gRae6n6Z74nJBf547nlMzSmDE+QVdHAGHzFot4sUeyuaeJoBr8HSABKGE64IFcplEHf5c5c/Ml3LL00+3MHGwTvaRx7uRLZzVC+ta0wcy0SiBkRXu0WeZ9cpzOj3Feh7CE8RftBM3Uwidm5ms8uTxF9PeffeTvxV1NG0QahvPPAnSUhhMTAa
  template:
    metadata:
      creationTimestamp: null
      name: cnpg-r2-creds
      namespace: cnpg-system
