apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-1h
  namespace: longhorn-system
spec:
  name: snapshot-1h
  task: snapshot
  cron: "0 * * * ?"
  retain: 24
  concurrency: 1
  groups:
    - default
    - test
  labels: {}
  parameters: {}
