---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cartarch-mcp-secrets
  namespace: mcp
spec:
  encryptedData:
    CARTARCH_DEV_API_URL: AgB6XF5zxrDxPC1IqgO2lrXeuGvk2BkpoRBJko/Dp2nfbjdVSFXtF7cFAzjkN/r0husNnw234Jvh7f2jwh4bFtJpd7hGggISWAt4uvXPzEc5pfeaWG7dcPmZkX37hMrSLipDFjeZSF+mCrBsEEX2O38SwLIM+jEih+omJ0uJ912iezNFNu3sOr40K8b6F41k+Ksnd/Q5zGQL//4xB45xoPaBZ9MqcSb0ATegK/UaSkegivXItdAqTUlkkKjzgkjev8y3PBtCcjn/ro3TRUWQYE8NwGHIfq6LVrX8S32uEUDgqPj13HK/cLUBvHXAQHj82YJ6NFZFsaHxdEN0uSyOeSR3Fxrqc3kUyOw09lkOsdfeWqiPX+B8f6+vHxRR/C6GRyKyafnIrSBHsnVhI+D6Cfvx/CVQZQt7QpniOOc86b+0JBo0OO6rY6ZO55KB2vk/nh7Jl5TSefT10XA954DTxZTF5HXRjO1flZfogWy4IGHsuE1Oit//so2856ehs9Lo+48vx/bEEpTqSDRdQq/uY7RtLw5QTp/LmztebFySrZAHMtlv0+dChsZ9Qi85FfJvOxC4G9TieTy2wbZ/P2W5DBJfdnBgEUtdY12irdUq0yA2oum2km2v0UpruYuejCAvS2Z3q5nwznS8AMrTKnsYPva0v/1jFAFZe3Opl45FmYOq+HUoCiYHYzzUIh9OiPsDAo+WLgvUrnSgQpL1WAdybOAXfhXzaTgA
    CARTARCH_PROD_API_URL: AgAPET4EOwuz7EWvqYm6SxrzqBLP5625jQCSoa8qWhu35u74POL2EQ4XXCqJeqkZ8OYkgmhqGTgpApoo6SEH/zpYzC+CJWg3S65VOPstFOy1c+rw2cuhv0TvoJbtaDCwqxSn4zfyjHSLtLUXtKueSu0Zhe84iZWicGKus6IphKpCbVgC9aFJhdXzVVDiDjUTujDnxaRs0fSl6vvZVmzGtWuYu/a0KKD8U8FoUSBLd704p6RS8eiiRrkjoeOscZzRZgbqpbZjmz2mtK+EZkiRdm3HSNiyMwbMX9lDO4qDtqB4AO4DnOm7mHAI9HfVhXcv82LmsZPt8Dfo/tu7qXornggEMz8mesw6erHdVclRz1ppjlq3LyKk6ucb35wctyARMd6SL0WHn86l25bwM+HjDhT1P53wwEcYBXPZbf20sVIoD6BpaC68RL75Ourv2mMIVo5o4g2+4+Dpe36uoFmrsZ2IXJdYB4cWlTSly6+B5OfMnxuJCDvUJVLB9eSodYh3YIlhjTEkbOkuPrX2AxxF3bQy5qy/HXAguU4JWwZeb0F5hA9x1olyXaCkY3opapXYQL5Zvt8GIBs9+MF/cb+XssKflLz/M9hMDRK5ET3ODau3WHm81dykGjQIi+3cZx1e+XAic4bVH+aw2LIBOjVLFmZyR/L5w3jQYftKyppu3zdX4G2ZC4JtXidB70BEndW4QvJCLcifaTZH0wQ5AVLxAal0NMVqflmI0iLkQpKVd7aKjngkl63Ej4lp3JclZ6UCFYJRCACvPA==
  template:
    metadata:
      creationTimestamp: null
      name: cartarch-mcp-secrets
      namespace: mcp
