---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cnpg-r2-creds-dev
  namespace: cartarch-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgByFC8whsK+NMfmew9Sw2jfojur9rC8edfCXfIbz4h2XGeqTLxq3KrfGXGfbNx9mxwJd3E6a6Xzgb2mJ+AS6l4fxl79B3thRzZd55RP3RgzxGus7I/k9Casw64BwH5zokfYIHJ/0fqb+ngV/1kSFNQdsEF3YVMnTJIULTQwn8qjnKoBGwwEneiv/Xk4JCqUcP37y7/Sh/ttrM8lpPFPE74mROYutFt5WY/w3nOsP7B6f5P3lE7rfdkX/T5PEksUer8F3wQZZbwcGH6BLpYtSV7BEPP+zhSUnbkkb2NXssWETbfdZfo1kEnz28+RTnBsqdrDALeaWqoXIkwDD3WrgdAcrF91DW5Z5P0okSzFIWhsqQPCQhPYAQVXgFlGUgQ2vUe5v3XYTDDEGNcMPE0EBX9/PesSMt9zdXpAK7Z6gO0/OXHS5qn5Elycf3870rPag6iPHG7lKMpsJQpuUQPNc6v/10BaR2/HL4FWt8UwImfp4jUDS2qykpAW1kNugYljzu9f+4RNM7E29HRVI+DPaQze38En4svCLBmRwyHIgUaKvEb2m/Uivd9CdbpbyKPc3FZrycTlwAQzAuhW35XH9SYv0kfStkIW1FeicDucDHqBN4RG2TizIU4NjgmCFO87kxiwjZNkvFirLfdHdgo9yJsxaWUNF9gWZdArAjjXyNtqOIoB6RA+r/zu7CO2XqPU5tnErN/WZbqdhXfvTv8+KtDHn9EEqBUc3tUr8Fkd76GvZQ==
    AWS_SECRET_ACCESS_KEY: AgBDtl4iTsCst+U4Ao/3OBkjBDfREGunXc0zPQvtbyQbGzdzU4hdGTalnDWF87HL/L9/KW6ctlEusqckaOcPq9l+p5EMkALKvI7hVPCqhE7dYSNx8XAoEEQDUPzQZjeOci+lG0A5nqFHU0k5iwixgnN+vcktu0pVabkMkh+y3KzaNiKKamMFsSAc5hQoIhqOgtiwrrTN8RAxRoaDZoqNtgJXO50p5VXToj578Wc60wA/XzRYMTt7OJKORGZNzKBxmoyWB6jOXDzC5UPpsiZOv8HWKPcl3jooAEtn8QLNmiB2ReWyzEZuO4JUMG+sUSssc+IziY96pQ/q0Z0OnSyour8X429fp8LK6nEuUG9KjLkHZOTmflZnxTg6HfssWetaFvuF3MX9SoRMhiiFE6hpeHJTorreO0rxKrktS8qZbQTbIdq8Nh/xERn99EcspXmQbbWWhTTre7er/CEn9ByS7IQzoGdlKcECzH4LAKJyvwnbutjpdeim/xIfB3QcGIl0t8YT1sfDxksTr0wdUuk+iAlVBgvoBnT3ZGCtyrwNiLcm0g7LTyfCWuBCBrDQvA7zYa7C/HHlTddag9nme5FrbR1Qyv+OecoPIzBmAJA2Zxn8GZUV6niPKoHESTcnPLzKNY72bfVBXuUG4AlvRbmKBvxtp9xFm7KoKSu64jQNwaWomIan1kORLTkRG2qX8sR/BbWUG5UzvcRMBrXO2qlZVt4c7DfPggm5U7q9JkBF4kDOCrrMCnDv+kvvKL7vi/2TO7ig9NFiEaQeZ7l6UCjdVvkd
  template:
    metadata:
      creationTimestamp: null
      name: cnpg-r2-creds-dev
      namespace: cartarch-dev
      
