---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCIuaaDqNIEiQsxmrhbX8x8MCRYE+NiNRt+c9ea3TFsKkL0HdQjNs1JPYmSWr9kvVpTxcL+Lq9xnKFpZkbBa6+wOGMVhCraVFGC0CuTZLCLoqi28qFXAgojaKBDS2uPyTCYGoX3tlgvE79acw/zwFik2n1jbUIceXzTfnYuM2SVKqrwBrGW430YdgwTpcxGL9pLZF6h5aeH1RFW+yIAo3Q/rzhj95KIbgCIFJYJg6jfKkrmcV2YsYI15m45rvEfSf5t57/o98N7apD125/QZ4GMe1vBWyxjYvR2WZcAxAYYsJxzSpsgk5ZjtcttbySZXoOrM0jgCorbKTgo8qSjiJrt6Dprb//XzygPOYGniRsVQZnP/eIklFR7N9R8DNNtjFqX/aEVURzJQArn/p2NMSBzA4lhZkafwRqXKBPBRjJY9TbP1y4ogoqsQ/iuA0sdYW7vb25dT/UU8Fd0t2StpuXfLQgndLd/39heXmrmyt8hzJ1d341ufrd5iQ2lUOPBseglWnwpmyU19sTmiCo7C7vldZsWYixgjU9hnO7ZnMj0FHWV8t2/P8jG3/Rv02lz3rOAnbgHdf8w+5dM6C9JRvk9WtXivNZnBDMQfWAsBDKdFrd9KdN3bMRC1mo3wrX7aRjCgAsTMs+9DUB80Z27HPkyXlHMRaBDEnchdzcc06g2RGWxWgq90eXugAsp0HUNDBRyMrzWIc71qkR4DGNtwFgRAw==
    client_secret: AgBH19YHENxc2mwrE0TF8+n/Rp7V91YntXB2hBy8LBJiVUoostYrO4P3R/kdGNgBM5SGFnJ6qVLzX33syJEFhS8kSdwpbK3Uzb78bopNVIpscDgTjfAOBERPnlRRaKPhAAdyDGOwuQ6VJe5A3qeTpw4fkEYbYuOliGc2PTpvMxp6Xy0uInfF8venu/49NVSkCXDw8mbGLX3iV8uuJNJY0Bdo8Jj5Rv6fxP24VjMaiFfU6/vBlglwkjJMiLWnrWLUqi2UNoU75ifHPcA+cm1ZUOuPQqA3iRA7edAXjLlZRgXnjUlbrByfx/VUaBSrf6a9H2ej5eKfdQhvHg0SaPSz+r8iXLuSAfqakT6INuN3ZV9wmiMteZOPfDpy7lUwi4AQH3le8R9jA+8AdMEuvxeWakjnE/CRyUotS/aeBQCdxMCNnPTyQgvqsNDTSmW8wc8VQhHnDjuJDiCI+ENgH04Rfr5o6l552PXRBmvaTn4YMAzpTgBPyoVDjy29UQmkzlc26q4CFsO3Susm1uJipPZ6NldiKM/wXFR4FftYR1rnpd3QcDkkhn911RTL/d/6xHDas0P3XasGxJBYAI7Pb0A0QzXS7s/DVADXAR4ri/eg9SO49KsIYHNAtSub78q/q8Rnbzwb14FSSIlDCEYSPpRComABCQv4uE+95ta/Z9qttfEq7Tk3gR20Lxu9SlrRPSY6lRjjXfTMt5wJ3KE4OWkv1WLIY4yc07r91UfpNQ3j/hRm0fi27BLn7CS55WFHQRrsbqvIGwm0w4ahn/xyczakJM4=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
