---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cartarch-secrets
  namespace: cnpg-system
  annotations:
    # Unseal ahead of the Deployment (default wave 0) that reads these keys.
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    RESEND_API_KEY: AgB2ARVcBJGcylIE3VHKDLOV20AG1i8Pmlc8Xor6eCkIAadYBUB/92wt+BUmrmcu9+j9iR8mYs7DPpHOg+rtCWusyWCGFt0Bsdbt9RF4X/9BHp+Oxz7RuBbAfhsXIm+rpf7yD63JZtPvpjmubNua39AQvnp8w9w50aFWSCzfdPFazgHL9PdxcR+CvgRAjnVi2jmtCWzcxA49jvlaZMNA8i4OPyqiuaYEyxiikg+BGDMiQ+HxuY4MTUMGPkAqKOtLDR2idqkRz6sUyFRiRxxsWrJR+u07KVNh3vnxxDN8Yy02EJ0LdTqFEXxv6xYT1p1D2Cv0697EaRltQs6LuKCmu7ijqkmmUjAXUCdydQcvi4+c9O5Yg/MRWX/FDuGb16THbhzwYFsW9xRsRNP3R5DNyTFckBEdvJOZ7wpEjSzDJ5pgN8DKVhBUAYRvVv9DwH5ZMoOidNkEG9RyYSrUXfQyfjEeVZO+ZH9D3re1VJ0mkI2hlrbixxTgZdTnrfU88zVf/SV2ObX3aibMy8JHb+4QH9/PmgJ3KMYrifmurMjUihdrkL/PR91hFQH93XjgilaYFNZ/m+4lrrpfo1gtnaLmoOFHlleCtqIxm0wAkFtPDd1EjXZEF4frAsCnpxEIcNzw+2YL19NIWN3vRPXjJB+hZuQYATYzKElGfzdBi62d+pxkuuRO0k3pvJ/ahB4SPn0Ae+NFc9R1gcGt8ThyeK+iRsJHnprGhAVvj3dlii3h2lBVF8sxqWI=
    SESSION_SECRET_KEY: AgBx4dOakiMYhxUQ0LxNm22aACp/vdE0AxdWVdqhCrWIajz/DElCwI8Xa3qfmqe89Gd+JL9y7P0emb3h0ipsDm1nzKD5o8VFcyCvDnhjS7MvWruIU4YjjL7vB72J+I9Ad/KzgNHQP6dN8CXLTO4+5hRLtskGnO2LzGKPPgjqAf7BQXthcESl3r4se4HpnAguoYWyg8iFKHmgmv812f3ft8SsdeAUIJ+L4gcvRM0sS/grIegJwexRsL8iUS5ZUxgmPOu5Oxr0SOHg7Udgk3gtEvIRFjYOkKPp7bh6oqxyr6agRjuz3IW55XeVL+CIPSFgW4L2S4MtIufWkNvSW3UOkqFGR5xDeAbt2kQqF1GKgIm/xfHl3x5TuKiu9SfDpW+mn/duKvpf5QZOeDNRqTc3OeSJzZSsPhlcGMpfjGUxTLneDDDPN32TjTGze8Whfm0/PwmeSwgKHXWE4iQ9ZAL+4MVnXFTesdQYTccidCj3EJ9ED1BX5WiBY6CtCjMaBapNsSVeuOd/mnY+vdNbJKUMl6/DbJ2G65VYQ5m5pHXYt2v9x94RAWoVHP/4hWEaZBpm+wof/opq7FP3W+VZRd8NeocbOVwBTY69DMpnPss1OLp9M18tEk7yw9bVFAHB6myGpLFJti8jSpbuPiAHLYdHGTxRGy2FKvLK0sXDS4cLS5mPZfuG4fjk2YcQTUEIjMRZjdetDxrF3YwKwHbrYT2yfr+jMtmlWEmscDb8/vazvPQBMOoWZUZjm+Ja0uVj
  template:
    metadata:
      creationTimestamp: null
      name: cartarch-secrets
      namespace: cnpg-system
