---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-intake-secrets
  namespace: intake
spec:
  encryptedData:
    DISCORD_BOT_TOKEN: AgA7Bhbn+3f1HkiEA5njmGlhb/iRaSLHaz8KGhHRgj6hvztDPomATT7D+BAWEpr19CXvdQiaxlsnWKChBX/+66HgPGFrd490geXT3qP+qINio/7zvRbiiIXfS5Fz2Dvj75PRGMldb6OV8amY+IbQbHa+3MEKR/ILnPpY88pBsIo4cb84IHfUrjmbyQitfDJSxwNPQbC0e1jQB1PN91U+F+SeaKYT2OG1gVdKYPvEEznVhQ0fS9+Gtih1/mL6f0Offkzln48V20NoU8ZqGuMAA7Gvqi5jRws/N1Gld9HvaP5ZkQca1KfQ8miWeGr0m1Rm2s8Oo9SwpnDGKW9gu3+DB27KGAfrkS+NZwn+6h1JeprE0QsqEeNEXfd8kuhFFZCR4POQfMqQ6yYL4prz0UXcV0tP+FGL0iSVqQzhihJD9O9oir9hmwKlqskTifYJH1oaRjVdSjlqqOvXvoJZDd3hBBcyamCCfdG8YWbYrf1uoYbc/be4BAZMha2TrFqp/wfc0BkzS/caWm1hAZCnkbF6ZkwD5Rc6IMqn5V/IBeRDJXxA1Btc88xGNpNnMpYZr0STQzzbmBsvIT8RhUJ3KiwfGae+uwzVq7IHXXgSeAHypdIuDQseCEsQOoUEAKAJ0ASSHyeTlehBTArOAEP8HHDO9GMLZcHYHXP3GSU6sRS645Q5cSZYlhGdK8YV7ENMpIaEyW/xTs27illPjW1U+ipYXe8UfX5GCwik4DGsWJpUMWcuqtJ8+f3GTAskZ1pU+1ANNGWfMgDSJSPRER1IlmxD6nWLWfYPaq9F9zI=
    GITHUB_PAT: AgCn3CjFDOFaw6Tko52Kw0o9SifQ/OHl43g22QLwoVh0mXTUWPcrmBNihuWhYHcM/UT4Z2iSeGEL+QwgjmpdFHKN64uGO53gaqDA0AkQCsHnGOTC/rkh4DzD/rF5mvQcDCCp8sl0NUvZvK2bnIpmENlECfKJ8xVLGxCSNkPvqaJAyhDAuBprEUA7YAK1TMUpsF/PZVGb6HmxTskJZ9UHWGheuHi6heJvsuWiGYKQjtaTimSrg4MENY8MSnuBJb/NflRTevryWQ/t4drljum0RFV3xxhlel4OT3uNU7J1K7aP3XYCrWKrMdYJUEsR3MsqiaPeKIvkZd6Zbu9TDl35RTDDqqhM/DOiubLeocdk1jCgPVSRCV4k4zGCG49MbarMyi+AQIedLEhbYDI+ngx5n8N+piB0E9LVlh6mDtfJRcPPtTyibSQwkfxM3+NT2kA36ANVnuBInRLX8Suvm/zSDIoqZ7Svj5BcrKrJ/+kPSb7F7uSRxFiaqcEeUx14urdNtL8ST/wn2XpbNOFxUWJR2JLQn26EjHM91t0302TxK+oTYnmWlze13AMkQEZl9eZSw+wsRqBsi4AUo9zRSypnBxxisW47dIJGZuhten7kp7Cj5snQIqRJP6hgFg4a/Kqz2GiaKJhiyYe4ZUdld9HlOJLtBTWU17WohrGKGWISAbMQlTf6XYCX+nIFyD/2V9qRWxOMEjlghyKR+pHxQ+ruMyXT4yVjtxzDnM/3zUYw0tAvgoOuOnK12Xy/X7axyCUcxtHnGtahqNx3gb/2s1YIvr8KtKS8uNeEFr4fZD5TaFXSDHuYYPuRzsWsGf1WCc0=
  template:
    metadata:
      creationTimestamp: null
      name: discord-intake-secrets
      namespace: intake
