---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-intake-secrets
  namespace: intake
spec:
  encryptedData:
    DISCORD_BOT_TOKEN: AgBQ6V5aVpNhT3LWJOoopn6f7XTYhgLuuiNp+/M6MI6wMazUovn2HCorndQFrsKp/cOYis+xTQ9BLJECU+ZIuaCxNwSOdlzvmd2EAVaUBNLtCKOp0MTB1jyGGwri9ksyGpfNGMYnFQy9rMwceBuBeJ/HRuFzX5bGDHER16HDpa8S4O7M8IDUdSRb2jwMSZlZt/uRUG4KICKeFw0AupsXIculrCw3K8/fqJlSgLBzPQI3Vyv/fYx8+Q9MdnqSD/Il7AI5Fq08OFU/a0XxuMPB5dak0l8aFskp+Lsdqhib7U1OKZZAuJzDhLZMZE8Ueue/1C5mwos/L6KlqMINxoUHdXmOjJYc8P8YJU6Rpd7E1tnGDEckNm3xbUnQNGQmq10V5lBBT7LxGJ/vBrx5C2P3jWt1OTdplxdHv8lQS1zWxSMdN/dNo0OTNxixRkxLEAHrW809s69KxNhFCNKGHqAfDNrX9s8VERkf2eusiEolKt5/ngiw/AdHo3TgUVZ+H/bC/iMVp/oksYOOfRfoX2hCuFKWoAGajxyqLSS/7MT5EQ08mNn2puAfn6FbPitkK3ZJI8pc6Qvue8p/8beXCbUzzw1v7uXsaUw9Zq9aLnlAdM5tBkU1KYYSYEOEo/gtbXbthmeH7Xp6iLNWqjQA31BpXrlWB61lABd4tk8T7WNo/xctNL3wpSj8moBuLhd6GcolvTUjlajmBJyo12G4i0g89zzN93p8TuBBpstU/ebhIUi2/T8kUQiZdgS3slWj1G37Nry8IFxDspj3lVAWuc6MxYF42RmA3YIcuUY=
  template:
    metadata:
      creationTimestamp: null
      name: discord-intake-secrets
      namespace: intake
