apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml  # re-enabled 2026-05-29: /metrics is live as of cartarch v3.30.23
  - ingress.yaml

images:
  - name: ghcr.io/jasonvandeventer/mana-archive
    newTag: v3.30.15
