apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obsidian-mcp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jasonvandeventer/vanfreckle-platform.git
    targetRevision: main
    path: k8s/apps/obsidian-mcp/overlays/homelab
  destination:
    server: https://kubernetes.default.svc
    namespace: mcp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
