apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-cartarch-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/jasonvandeventer/vanfreckle-platform.git
    targetRevision: main
    path: clusters/talos/manifests/cnpg-cartarch-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    - group: postgresql.cnpg.io
      kind: Cluster
      name: cartarch-prod
      jqPathExpressions:
        - '.spec.postgresql.parameters'
      jsonPointers:
        - /spec/postgresGID
        - /spec/postgresUID
        - /spec/logLevel
        - /spec/failoverDelay
        - /spec/maxSyncReplicas
        - /spec/minSyncReplicas
        - /spec/enablePDB
        - /spec/monitoring
