config:

  argocd:

    serverAddress: argocd-server.argocd.svc.cluster.local

    insecure: true


  logLevel: info


  git:

    commitUser: "Argo CD Image Updater"

    commitEmail: "noreply@local"


extraArgs:

  - --interval=2m

