---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: image-updater-git-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgAZfOr51V16SYGtjzazNer5v+yVxJA97UThAgvWvtDquWF0Hp1o3pmyiRoLhBHRDF8McPD0+sTGpaIzSvVV9o5hhTNOQK4K5XcahtGK9akOIMIqEwOzOxZTcrgvTpjswqR7/vVPIKvCmJxew66HFwvFoAANa/JqViXI/qBYJps6L6GBnbZQ0TndrMb09/1bK3DG+FCYHLnZ/o3bDPY2UUvQZxMp/XnSwpJsfL3GW8MeIIW24eHlhYKvuuAGCKlEklSmEPQsB7TCqVC9uV0DSki0BamoG82wnGIXhtWGoKMxoNWLZfv4MuQ3qUboLIzrbMCOltH3R/8T3dCA1N8jWkLJjHZD1vxx6oVPC8WnH3TiocStO3ZBVS5v+rl4tJ8xmdgQEIoP1myHu2vzYfmnh07XBZPdY7XE1oEqAHOZQhS1HAuS7EiVQzaP1Zt4HNYIFEMmXqB3S5+3QdTlQhWLKf8nQ+B3OrUtnvOemFf6yJtZMHR8RuDKCYQHyhJpQNe7hCI+V/M080c87bTldWsk2oErqemiABu226pZ/bTycbY/krkWHxLk3tSmR7q6b0RA2lHfbvDD3soPvOnEBtYdDqUB2Er39402nRT05zOBuOMghBE5VFFgPvTqZlcI2xuIpY1S5qaUuyYZO6dxtylv1muwh9V6bDJ+mXDWbhj2G5rCMNGvgDalo33NwNoD0WDYhZGNYAJcZB6wwC8y8LxNcntur9Eu5nNeOQaeBMRnOK/8K86hGIUoV42l
    username: AgBTLJsczPp2v9cMHYBv9VIcjfrkoHmd70ZUYjqy45hkS3/Zb/aZYGrPrNkCRq1Yge5JxrSnZ/NGe+pSVtr8heGzLqkuzdQWV9P3DUJADh9QL2LDirGFR2Tes+ka0u0OwMDNI99f7mbXrWUbCUf0FkxebHEEs5v+wLP8xblP7v+cXR7OmF33B20t/BhGV7JOzu6sBW3SayKQc/fW10C3F3iDA8YqG2JbmXBkc6PG8/U/8TQdQHTv+JxaYefb6jjxSiBY+9GaDmFaligtkhNMQWb/mJ1JSCsN1tt/JhtRbphlR1j94JChvAiDe/Wej6WM+qkNN9NMFDc8b2OGauW6iHDHFJJoUvP/tsw/EkKzNsV2tEJlB+gVv+KFtlKLJS+mW02pkMIqZLuvy8uaAyVLKRpgjMbEZraz8s49OaluMg7vl9hX9fwRztjboQk+XaRsnr5w0GtAN+M/zFg/x1PzncLZujVbpDiaEXwQtaiudVio03ML5RIgGCdAgY2bPkD9MJg/7l5en5Trt6Gy0AsXvAqBH6mc69HoJxXgZMBnkJtDGU1wIGv0xbLFedA23DRyFJ6TvPrP0Gu4d+rCyb94ySfmlRLJ5rMlX7gcsqsL3wuYYjy1JQX9op7WrFUqNrRc831Gb/OTLxGXTvrQ4TEw9CM98eSS0FwiWyOioKneeiRC45NTkMTOOwBdwo9mV3rgFkuTt+MTbiwgq7/3aqPYvwFl
  template:
    metadata:
      creationTimestamp: null
      name: image-updater-git-creds
      namespace: argocd
