---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cartarch-mcp-db
  namespace: mcp
spec:
  encryptedData:
    CARTARCH_DB_DSN: AgAX9U2N5JZKsO37UAO/ahTYYAJeceM9CX7bhZYZYZ3d1bx6avHDbenGFgYjT0sFuXWLleWgF7ZQ7+VfwVpSOhKG3oRSlwVqFwPVIF/1v8s7ijJ7rR5rC6ai87BZAIDWEVbQbGp2TB+/AML1rKbkeYkBl1BXFQmKHE3D1c9KoRDBT+L9sMB7KbqaOb1abxJ7PZcd6sa4BP/YPib1U2wPdhFcqpJKhbjqDZEdichXjfHDbiE+KHhPfNycAfqB4EmrYW0toDQrBXQ5IVhFh+0uqId/aB+ilHZPLLUipqwTnFUz8jWgtWDH2hD5ip0JkczMBC1GjPQcRUmGGZ/YUA7LFhF11HCjRjqwLX9FdU/RYtHivRxQKGPXqX36Xo+yog6gdinKiDRSPOToQCdO9vDdvFIs/kNyiZV3AQsHv/8oo8DGC3tI/p8WwPfsPxGCQ3WfJCWdn/+r2c9RzGpIrt2vu4uu+FVr7+m4rFH5t4b6soFGKH/wS8G8t3ndV6ocSorPClMT+6fwJBYzNUJvgsBAL8vjFutwShxIyn3PxfFoqNExDFFboa8ovYx5s7InGcWxrSOqxBxcTnz8Qmtm2uS8msF/uVVixxzSd6c78pfrZjgpgKinjVi1gTpRdEccyf4BLVEsqHV8VmSYhtsdXt5ehqkk0AwlqHu22hmBwsmbF3mWF1bJaxrpimk1Zr2+nhGRpVnY9aIbgbnjlm2fwAh87SsGY541Nq0sYpoXme725V/xJhmdaZeBtQq9mUaqM4cZYieob3eNfpdpXTrwH1T12Euvifgjk8ZpFQgAMk+ZxvEDq+IppOXjodgt0RbPeNundfbsV8oVlRVJURzJlZU1OPGBg4AYW3GAfw==
  template:
    metadata:
      creationTimestamp: null
      name: cartarch-mcp-db
      namespace: mcp
