---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-mcp-secrets
  namespace: mcp
spec:
  encryptedData:
    github-pat: AgAQgNn7eKnwDp/i1YEdIYOicV1pLK7WY98CzrZFmhxEHWgAxJti6tkalYeOwAc4S0TwefDqEMoQm6w9FNyRRtN6eNmBFbwwCZTnSm9M5R5xP8vbbOcvVA/cWkBogaTByO41DXdINjU3iODpFO3TVoQejgNSLGfDFmKi19geCeNAG7XiCKNxNOhUAS9nv4BF6k2pKK2z2bo/D8N+1LtgJgr3ABLw3rWG7I8Rs4E96EscT27sophe7lLy0/knfG2XZ34S0Eta9eA6tNADlgU1Ej1yBoGbpFAL8GrL3H7YUx4vssEoWDHRuVIjYvnfXtHMck+SjguVwMffNvDc6WpZo5Jw8kbeHbFyGmYpV+m9C1kR+GxzlJaUp/7X1kmsoLgtmGtShY5s9wjn9gBhNLQa5O5yO8mSronlsxOmr8D2EKPxcwHdsj0ddWMBl6cMuaqdEUP7+eHy3ZiK30XVorhrp0NIrIAqnHqfqYKX7VV+FHwaNd7kP8tEymNL9DxNnozRf4gRAfMrpO5g1A0p8foZ3EjmU+apRKWEctZab9HU3gXWJk87Agp7skueMouSB6khz/Om7OPm6+Rp267141je/NLS+3ZV3iRKTXLCQ2PLl35Bf8kTtqxE1CLWybuGVeJP75XJBaqM+lIRi+YAO0tsyhtNwBX8B7GYP7PTJrfswpVHqSTENnyB/RwUn6myhWpZQGpPSJ/jtCNCC/jgoiFpIRfdyR+RAk3lzsvO3ZzaGzzn/EEmMIUFioQ4vh5VET/9llxXHHPdLVurYYQWvtyhNAzXSlxOznt6lbUNGpMiMQNIb0vg2Qu5v2yIxWJKURU=
  template:
    metadata:
      creationTimestamp: null
      name: github-mcp-secrets
      namespace: mcp
